Account and address index support
ElrondNetwork/hw-app-elrond pull request #9
Opened 2021-11-08 15:15 UTC by bogdan-rosianu

added support for account and address index (only for >= v1.0.16 ledger apps)

Test:
![image](https://user-images.githubusercontent.com/51945539/140767606-f5a911a0-3705-431e-b71b-464dbe2821a3.png)
Result:
![image](https://user-images.githubusercontent.com/51945539/140767661-8594147e-d065-47c9-b848-11629effcb1c.png)

2021-11-08 17:04 UTC, arhtudormorar submitted a review, later dismissed

2022-08-08 09:20 UTC, ccorcoveanu requested changes
@bogdan-rosianu wow, old PR. If it's still of interest, can you please fix the package.json conflicts so we can merge? I am trying to close PRs on this repo and see if we can move it in the bigger provider repo

2022-11-21 11:56 UTC, ccorcoveanu approved these changes

2022-11-21 12:19 UTC, arhtudormorar approved these changes

2022-11-21 12:24 UTC, merged